# Generated by Django 4.1 on 2022-09-02 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0002_profile_delete_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="id_user",
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
